title: CoWriting-Kazakh
author: Wafa Johal
email: wafa.johal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CoWriting Kazakh is a research project aimimg to help children with the transition from cyrillic to latin alphabet in the Kazakh language.
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
